// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               v5.29.0
// source: order.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "order";

export interface OrderInfo {
  name: string;
  description: string;
  price: number;
  quantity: number;
  userId: string;
}

export interface OrderList {
  orders: OrderResponse[];
}

export interface UpdateOrderById {
  name: string;
  description: string;
  price: number;
  quantity: number;
  id: string;
}

export interface OrderId {
  id: string;
}

export interface OrderResponse {
  id: string;
  name: string;
  description: string;
  price: number;
  quantity: number;
  updatedAt: string;
  createdAt: string;
  userId: string;
}

export interface EmptyResponse {
}

export const ORDER_PACKAGE_NAME = "order";

export interface OrderServiceClient {
  buyProducts(request: OrderInfo): Observable<OrderResponse>;

  getOrderById(request: OrderId): Observable<OrderResponse>;

  getOrders(request: EmptyResponse): Observable<OrderList>;
}

export interface OrderServiceController {
  buyProducts(request: OrderInfo): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  getOrderById(request: OrderId): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  getOrders(request: EmptyResponse): Promise<OrderList> | Observable<OrderList> | OrderList;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["buyProducts", "getOrderById", "getOrders"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
