// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               v5.29.0
// source: order.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "order";

export interface OrderInfo {
  name: string;
  description: string;
  price: number;
  quantity: number;
}

export interface UpdateOrderById {
  name: string;
  description: string;
  price: number;
  quantity: number;
  id: string;
}

export interface OrderId {
  id: string;
}

export interface OrderResponse {
  id: string;
  name: string;
  description: string;
  price: string;
  quantity: string;
  updatedAt: string;
  createdAt: string;
}

export interface EmptyResponse {
}

export const ORDER_PACKAGE_NAME = "order";

export interface OrderServiceClient {
  createOrder(request: OrderInfo): Observable<OrderResponse>;

  getOrderById(request: OrderId): Observable<OrderResponse>;

  updateOrder(request: UpdateOrderById): Observable<EmptyResponse>;

  deleteOrder(request: OrderId): Observable<EmptyResponse>;
}

export interface OrderServiceController {
  createOrder(request: OrderInfo): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  getOrderById(request: OrderId): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  updateOrder(request: UpdateOrderById): Promise<EmptyResponse> | Observable<EmptyResponse> | EmptyResponse;

  deleteOrder(request: OrderId): Promise<EmptyResponse> | Observable<EmptyResponse> | EmptyResponse;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOrder", "getOrderById", "updateOrder", "deleteOrder"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
