// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               v5.29.0
// source: user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface UserId {
  id: string;
}

export interface UserEmail {
  email: string;
}

export interface CreateUser {
  login: string;
  email: string;
  password: string;
}

export interface UserResponse {
  id: string;
  login: string;
  email: string;
}

export interface AllUserResponse {
  id: string;
  login: string;
  email: string;
  password: string;
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  getUserById(request: UserId): Observable<UserResponse>;

  createNewUser(request: CreateUser): Observable<UserResponse>;

  getUserByEmail(request: UserEmail): Observable<AllUserResponse>;
}

export interface UserServiceController {
  getUserById(request: UserId): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  createNewUser(request: CreateUser): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getUserByEmail(request: UserEmail): Promise<AllUserResponse> | Observable<AllUserResponse> | AllUserResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getUserById", "createNewUser", "getUserByEmail"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
